import React from 'react';
import PrimaryButton from '../../Componentes/Button/PrimaryButton';

const Setp2 = () => {
    return (
        <div className="secondSection">
            <div className=' py-5 '>
                <h2 className='text-[24px] py-2'>Would you like an autogenerated layout based on the information you have provided or would you like to select every space yourself?</h2>

                <button className="lg:max-w-sm bg-[#4C5678] input input-bordered w-full my-2 ">Autogenerated layout</button> <br />
                <button className="lg:max-w-sm bg-[#4C5678] input input-bordered w-full my-2 ">I'll select the spaces myself</button>
            </div>
            <PrimaryButton content='Back' bg='white'></PrimaryButton>
        </div>
    );
};

export default Setp2;